version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20050:20050"
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20050/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
